### ISSUE TITLE
Cannot open include file  "ugeometricbrush.lrs"Fatal: (1018) Compilation aborted

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/lazpaint-upstream#1] opened 2020-05-22 21:51 UTC
Hello.

Great the idea to give all needed for `LazPaint`!

When compiling (with `ideU`) there is that error:

```
/lazpaint-upstream-master/lazpaint/ugeometricbrush.pas(104,4) Fatal: (2013) Cannot open include file
 "ugeometricbrush.lrs"Fatal: (1018) Compilation aborted
```

That file is produced by `Lazarus`.
Do you have a idea how to produce `lrs` files without using `Lazarus`?

Note that all the rest of compilation is ok with `fpc 3.0.4`, and no more `bgrabitmap` and `bgracontrols` macros are needed, all can be done now with `../bgrabitmap` and `../bgracontrols`.

But compiling with `fpc 3.2.0.`, there are errors like this:

> bgratypewriter.pas(595,49) Error: (3349) Only static methods and static variables can be referenced through an object type
> bgratypewriter.pas(598,91) Error: (3349) Only static methods and static variables can be referenced through an object type
> bgratypewriter.pas(614,56) Error: (3349) Only static methods and static variables can be referenced through an object type

**Comment by fredvs** [comment] 2020-05-22 22:09
Hello.

OK, did compile `LazPaint` with `Lazarus`, and copy all the `.lrs` into 
`/lazpaint-upstream-master/lazpaint/` and now it compiles ok with `ideU`.

Note that a `.lrs` is the same for all OS 32 or 64 bit.

Note also that compiling for Windows I get that error:

> lazpaint.lpr(103,55) Error: (5000) Identifier not found "SysToUTF8"
> lazpaint.lpr(121) Fatal: (10026) There were 1 errors compiling module, stopping

Where is that `SysToUTF8`?

Last note: all compiles and run ok with source of `/lazarus/2.0.6/`

With `lazarus-trunk` is compiles OK but crash at run.

```
Error reading ComboBox_ArrowStart.ReadOnly: Unknown property: "ReadOnly".
Press OK to ignore and risk data corruption.
Press Abort to kill the program.
```

Et voila, all inspected!

Included all the `lrs` and l`azpaint.prj` for this `lazpaint-upstream`.

[all.lrs.zip](https://github.com/bgrabitmap/lazpaint-upstream/files/4670620/all.lrs.zip)

[lazpaint.prj.zip](https://github.com/bgrabitmap/lazpaint-upstream/files/4670932/lazpaint.prj.zip)

**Comment by fredvs** [comment] 2020-05-22 23:33
> Note also that compiling for Windows I get that error:
>   lazpaint.lpr(103,55) Error: (5000) Identifier not found "SysToUTF8"
>   lazpaint.lpr(121) Fatal: (10026) There were 1 errors compiling module, stopping
> Where is that SysToUTF8?

OK, I get it, it is in `LazUTF8.pas`.

Maybe you may add this in the uses section of `lazpaint.lpr`:

```
uses
 {$IFDEF WINDOWS}
  {$if FPC_FULLVERSION>=030001} LazUTF8, LazFileUtils, {$endif}
  {$ENDIF}
```

So for me, with the all `lrs` included and the change in `uses` section, all is out-of-the-box, for all Unixes and Windows.

And I let you in peace!

**Comment by circular17** [comment] 2020-05-23 07:06
I think I fixed all the problems:
- no need for LRS files anymore
- LazUTF8 unit for Windows compilation
- add static for FPC 3.1+
- added ideU project
- remove unnecessary ReadOnly property

Can you check it works for you?

**Comment by fredvs** [comment] 2020-05-23 10:41
> Can you check it works for you?

Yes of course but tonight only.

**Comment by circular17** [comment] 2020-05-23 11:07
When you want.

**Comment by fredvs** [comment] 2020-05-24 14:10
Hello.

Before to jump into the Rpi, I did try the MakeFile with Linux 64:

```
fred@fiens ~/D/lazpaint-upstream-master> ./configure
For help type: ./configure --help
Prefix set to /usr/local
Using lazbuild
You can now type: make

```

Then:

```
fred@fiens ~/D/lazpaint-upstream-master> make
echo lazbuild or fpc will determine what to recompile
lazbuild or fpc will determine what to recompile
lazbuild bgrabitmap/bgrabitmappack.lpk
/bin/bash: lazbuild : commande introuvable
make: *** [Makefile:129: bgrabitmap] Error 127

```

This with last `lazpaint-upstream` commit.

**Comment by fredvs** [comment] 2020-05-24 14:30
OK, here tested on Linux 64 with included `LazPaint.prj`:

First shot with `fpc 3.0.4`:

```
/lazpaint-upstream-master/lazpaint/lazpaint.lpr(120,1) Error: (9031) Can't open resource file "/home
/lazpaint-upstream-master/lazpaint/lazpaint.res"
/lazpaint-upstream-master/lazpaint/lazpaint.lpr(120,1) Fatal: (10026) There were 1 errors compiling 
module, stoppingFatal: (1018) Compilation aborted
```

(Hum, you still added `{$R *.res}` for Unix too...)
[EDIT] Removed `{$R *.res}` for Linux did compile OK.
[EDIT2] Dont forget this:
https://github.com/bgrabitmap/lazpaint/issues/166

And compiling with `fpc 3.2.0` or  `fpc 3.3.1`:

> lazpaint-upstream-master/bgrabitmap/bgratypewriter.pas(598,91) Error: (3349) 
> Only static methods and static variables can be referenced through an object type

**Comment by circular17** [comment] 2020-05-24 15:14
That's normal, because you don't have Lazarus installed. To compile with FPC only, use:
```
./configure --lazdir=LAZARUS_DIRECTORY
make
```
It will generate the RES file.

If you want to compile from ideU, you can just generate the RES file with:
`./makeres`

**Comment by fredvs** [comment] 2020-05-24 15:16
> I think it will work as well for Raspbian as it is a Debian. Can you try by doing the following?
> 
> ./configure --lazdir=/your/lazarus/source/directory
> make


Ooops, I did not see this from a other issue:

So, doing that:

`$ /configure --lazdir=/home/fred/lazarus/2.0.6/`
`$ make`

Gives this (WOW):

> (9022) Compiling resource release/lib/lazpaint.or
> (9015) Linking release/lazpaint
> /usr/bin/ld : avertissement : release/link.res contient des sections de sortie; avez-vous oublié -T?
> (1008) 512744 lines compiled, 16.5 sec
> (1021) 495 warning(s) issued
> (1022) 5009 hint(s) issued
> (1023) 56 note(s) issued
> mkdir -p -p icons
> declare -A icons=([0]=256x256 [1]=48x48 [2]=32x32 [3]=16x16 ); for i in "${!icons[@]}"; do convert lazpaint/lazpaint.ico[$i] icons/${icons[$i]}.png; done
> convert-im6.q16: InvalidImageIndex `lazpaint/lazpaint.ico' @ error/list.c/CloneImages/281.
> convert-im6.q16: subimage specification returns no images `lazpaint/lazpaint.ico' @ error/constitute.c/ReadImage/642.
> convert-im6.q16: InvalidImageIndex `lazpaint/lazpaint.ico' @ error/list.c/CloneImages/281.
> convert-im6.q16: subimage specification returns no images `lazpaint/lazpaint.ico' @ error/constitute.c/ReadImage/642.
> convert-im6.q16: InvalidImageIndex `lazpaint/lazpaint.ico' @ error/list.c/CloneImages/281.
> convert-im6.q16: subimage specification returns no images `lazpaint/lazpaint.ico' @ error/constitute.c/ReadImage/642.

And `/lazpaint-upstream-master/lazpaint/release/lazpaint`
was created.

WOOOW.

**Comment by fredvs** [comment] 2020-05-24 15:17
> That's normal, because you don't have Lazarus installed. To compile with FPC only, use:
> 
> ./configure --lazdir=LAZARUS_DIRECTORY
> make

Yes, I did found it, sorry.

**Comment by fredvs** [comment] 2020-05-24 15:24
> It will generate the RES file.

Hum, not sure it is the optimal way, I would not add  {$R *.res} for Unix and use icons in form.
But ok, it works here on a full kitted machine (not sure on a Raspbian iso not customized).

**Comment by circular17** [comment] 2020-05-24 15:28
Cool.

Though there is a problem with the icon extraction (which is useful for the Deb package).
`convert-im6.q16: InvalidImageIndex 'lazpaint/lazpaint.ico' @ error/list.c/CloneImages/281. convert-im6.q16: subimage specification returns no images 'lazpaint/lazpaint.ico' @ error/constitute.c/ReadImage/642.`

The command you wrote would not work:
`/configure --lazdir=/home/fred/lazarus/2.0.6/`
It would rather be:
`./configure --lazdir=/home/fred/lazarus/2.0.6`

Though I doubt that this was the problem.

**Comment by circular17** [comment] 2020-05-24 15:29
What if you do the following?
`convert lazpaint/lazpaint.ico[0] icons/256x256.png`

**Comment by fredvs** [comment] 2020-05-24 15:47
OK.

I did retry from scratch.

First delete directory `/lazpaint-upstream-master`

Then unzip last commit of `lazpaint-upstream-master` and in console:

   - $ cd ~/lazpaint-upstream-master
   - $ convert lazpaint/lazpaint.ico[0] icons/256x256.png

> convert-im6.q16: unable to open image `icons/256x256.png': Aucun fichier ou dossier de ce type @ error/blob.c/OpenBlob/2874.
> convert-im6.q16: WriteBlob Failed `icons/256x256.png' @ error/png.c/MagickPNGErrorHandler/1641.
>

**Comment by circular17** [comment] 2020-05-24 15:50
Ah if you do from clean, then first create the _icons_ directory with `mkdir icons`.

**Comment by circular17** [comment] 2020-05-24 15:51
> Hum, not sure it is the optimal way, I would not add {$R *.res} for Unix and use icons in form.
> But ok, it works here on a full kitted machine (not sure on a Raspbian iso not customized).

Well you can try on a Raspian later. :-)

**Comment by fredvs** [comment] 2020-05-24 16:01
> Ah if you do from clean, then first create the icons directory with mkdir icons.

Hum, ok.

So first `make clean`
then `convert lazpaint/lazpaint.ico[0] icons/256x256.png`
then `make`

Gives this:

> (9022) Compiling resource release/lib/lazpaint.or
> (9015) Linking release/lazpaint
> /usr/bin/ld : avertissement : release/link.res contient des sections de sortie; avez-vous oublié -T?
> (1008) 512744 lines compiled, 15.4 sec
> (1021) 495 warning(s) issued
> (1022) 5009 hint(s) issued
> (1023) 56 note(s) issued

Yes, this one seems good.

**Comment by fredvs** [comment] 2020-05-24 16:03
> Well you can try on a Raspian later. :-)

Yes I prefer that all is working perfectly on Linux 64 before to jump into the Rpi.

**Comment by circular17** [comment] 2020-05-24 16:06
> So first `make clean`
> then `convert lazpaint/lazpaint.ico[0] icons/256x256.png`
> then `make`

No no no. Just:
```
make clean
mkdir icons
convert lazpaint/lazpaint.ico[0] icons/256x256.png
```
And show me the output.

> Yes, this one seems good.

That was already good before. The folder _icons_ is only necessary when building Deb package.

**Comment by fredvs** [comment] 2020-05-24 16:10
```
fred@fiens ~/D/lazpaint-upstream-master> make clean
rm -rf "bgrabitmap/lib"
rm -rf "bgrabitmap/backup"
rm -rf "bgracontrols/lib"
rm -rf "bgracontrols/backup"
rm -rf "lazpaint/debug"
rm -rf "lazpaint/release/lib"
rm -f "lazpaint/lazpaint.res"
rm -f "lazpaint/release/lazpaint"
rm -f "lazpaint/release/lazpaint32.exe"
rm -f "lazpaint/release/lazpaint_x64.exe"
rm -rf "lazpaint/backup"
rm -rf "lazpaint/test_embedded/backup"
fred@fiens ~/D/lazpaint-upstream-master> mkdir icons
mkdir: impossible de créer le répertoire « icons »: Le fichier existe
fred@fiens ~/D/lazpaint-upstream-master> 
convert lazpaint/lazpaint.ico[0] icons/256x256.png
fred@fiens ~/D/lazpaint-upstream-master> 
```

**Comment by fredvs** [comment] 2020-05-24 16:11
Maybe you asked to do from scratch, so I come back in a few minuts.

**Comment by circular17** [comment] 2020-05-24 16:11
Hmm ok, so no error here for the icon.

**Comment by circular17** [comment] 2020-05-24 16:11
> Maybe you asked to do from scratch, so I come back in a few minuts.

No no doesn't matter.

Oh I made a mistake. It would be with distclean. Also let's try another image 48x48:
```
make distclean
mkdir icons
convert lazpaint/lazpaint.ico[0] icons/256x256.png
convert lazpaint/lazpaint.ico[1] icons/48x48.png
```

**Comment by circular17** [comment] 2020-05-24 16:15
Then in the icons folder, you would get 2 images.

If that doesn't work, maybe the icon format is not properly recognized. You can check that with:
`identify lazpaint/lazpaint.ico`
which for gives:
```
lazpaint/lazpaint.ico[0] PNG 256x256 256x256+0+0 8-bit sRGB 94.5KB 0.000u 0:00.000
lazpaint/lazpaint.ico[1] ICO 48x48 48x48+0+0 32-bit sRGB 94.5KB 0.000u 0:00.000
lazpaint/lazpaint.ico[2] ICO 32x32 32x32+0+0 32-bit sRGB 94.5KB 0.000u 0:00.000
lazpaint/lazpaint.ico[3] ICO 16x16 16x16+0+0 32-bit sRGB 94.5KB 0.000u 0:00.000
```

**Comment by fredvs** [comment] 2020-05-24 16:18
Would it be possible to add a option: compiler?

./configure --lazdir=LAZARUS_DIRECTORY --fpcexe=FPC_FILENAME

**Comment by fredvs** [comment] 2020-05-24 16:21
```
fred@fiens ~/D/lazpaint-upstream-master> make distclean
rm -rf "bgrabitmap/lib"
rm -rf "bgrabitmap/backup"
rm -rf "bgracontrols/lib"
rm -rf "bgracontrols/backup"
rm -rf "lazpaint/debug"
rm -rf "lazpaint/release/lib"
rm -f "lazpaint/lazpaint.res"
rm -f "lazpaint/release/lazpaint"
rm -f "lazpaint/release/lazpaint32.exe"
rm -f "lazpaint/release/lazpaint_x64.exe"
rm -rf "lazpaint/backup"
rm -rf "lazpaint/test_embedded/backup"
rm -f "prefix"
rm -f "lazdir"
rm -f "debian/CONFIGURE_DEFAULT_LAZDIR"
rm -rf "icons"
fred@fiens ~/D/lazpaint-upstream-master> mkdir icons
fred@fiens ~/D/lazpaint-upstream-master> 
convert lazpaint/lazpaint.ico[0] icons/256x256.png
fred@fiens ~/D/lazpaint-upstream-master> 
convert lazpaint/lazpaint.ico[1] icons/48x48.png

convert-im6.q16: InvalidImageIndex `lazpaint/lazpaint.ico' @ error/list.c/CloneImages/281.
convert-im6.q16: subimage specification returns no images `lazpaint/lazpaint.ico' @ error/constitute.c/ReadImage/642.
fred@fiens ~/D/lazpaint-upstream-master>
```

**Comment by fredvs** [comment] 2020-05-24 16:23
```
identify lazpaint/lazpaint.ico
lazpaint/lazpaint.ico[0] PNG 256x256 256x256+0+0 8-bit sRGB 79464B 0.000u 0:00.000
lazpaint/lazpaint.ico[1] ICO 48x48 48x48+0+0 8-bit sRGB 0.000u 0:00.000
lazpaint/lazpaint.ico[2] ICO 32x32 32x32+0+0 8-bit sRGB 0.000u 0:00.000
lazpaint/lazpaint.ico[3] ICO 16x16 16x16+0+0 8-bit sRGB 94550B 0.000u 0:00.000
fred@fiens ~/D/lazpaint-upstream-master> 
```

**Comment by circular17** [comment] 2020-05-24 16:28
Thanks. Ok so that may be a regression bug in **imagemagick** with version 8:6.9.10.23:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921134

I have version 8:6.9.7.4 which works fine. Which version do you have?

**Comment by circular17** [comment] 2020-05-24 16:45
> Would it be possible to add a option: compiler?
> 
> ./configure --lazdir=LAZARUS_DIRECTORY --fpcexe=FPC_FILENAME

Ok, that's done. The option is **--fpcbin=**

**Comment by fredvs** [comment] 2020-05-24 16:47
> I have version 8:6.9.7.4 which works fine. Which version do you have?

How to get the version?

**Comment by circular17** [comment] 2020-05-24 16:50
It is shown in synaptic. Or you can type:
`apt-cache policy imagemagick`

**Comment by fredvs** [comment] 2020-05-24 16:53
```
 apt-cache policy imagemagick
imagemagick:
  Installé : 8:6.9.10.23+dfsg-2.1
  Candidat : 8:6.9.10.23+dfsg-2.1
 Table de version :
 *** 8:6.9.10.23+dfsg-2.1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by circular17** [comment] 2020-05-24 17:02
Hmmm, that's not convenient. Maybe you can install an older or a newer version of it?

**Comment by fredvs** [comment] 2020-05-24 17:20
>  Maybe you can install an older or a newer version of it?

It is the last one done with `sudo apt-get upgrade imagemagick`

**Comment by circular17** [comment] 2020-05-24 17:30
Maybe you'll find something there: https://imagemagick.org/script/download.php

There are RPM packages, and you say you can make a DEB out of it, right?

**Comment by fredvs** [comment] 2020-05-24 17:37
Hum, not sure to understand.

Do you asking to install a old version 7 from previous millennium vs the version 8 installed on the system?

Sorry but did not really understood what is the problem with version 8.

**Comment by circular17** [comment] 2020-05-24 17:52
Nope.

I think the 8: does not mean the version. Basically you have version 6.9.10. Maybe the bug is fixed in version 7.0.10.

The problem with version 6.9.10 is that it does not extract correctly the icon images. But they are needed to create the Deb package.

Note that if we cannot get this right, we could still do a package without the various icon sizes.

**Comment by fredvs** [comment] 2020-05-24 18:07
> Note that if we cannot get this right, we could still do a package without the various icon sizes.

What Debian fork do you use, Mint?

Imho, deb packages should be synchro with original Debian 10.
How did you install imagemagick?

Because the version I have will be used by many people so if no solution is found, maybe a package without various icon sizes would be safer.

**Comment by circular17** [comment] 2020-05-24 18:22
Yep I am on Linux Mint. It lags a bit behind.

Hmm yes, maybe we can do without the various icon sizes. Or provide them as part of the upstream.

**Comment by fredvs** [comment] 2020-05-24 18:31
Hum, to understand all.

What appends using the various icon sizes in deb and my imagemagick version?

Ok, there is a error message for some extraction, but is the first icon extracted or no?
If the first is extracted, then the various icon sizes can be used and tant pis for the error messages.

And for Mint users, you will have the 3 icons without errors.

**Comment by circular17** [comment] 2020-05-24 18:37
> What appends using the various icon sizes in deb and my imagemagick version?

Well either it creates an image but without content, so the icon would be invisible.
Or it does not create the image, and the "make install" will fail.

Ok I've added the icons in the upstream. So using this, you can try to make the Debian package.
https://github.com/bgrabitmap/lazpaint/issues/164#issuecomment-633218649

**Comment by fredvs** [comment] 2020-05-24 18:41
OK, I will try it tonight.

**Comment by fredvs** [comment] 2020-05-24 18:47
And concerning {$R *.res} for Unix and use icons in forms?
(This before to jump in RPi)

**Comment by circular17** [comment] 2020-05-24 18:49
I suggest to try and see as it is on Raspbian. Why wouldn't it work?

**Comment by fredvs** [comment] 2020-05-24 19:36
> Why wouldn't it work?

Because `windres` is not installed (and my Rpi is not connected to internet).

**Comment by fredvs** [comment] 2020-05-24 20:19
bgrabitmap/lazpaint#164 (comment)

```
fred@fiens ~> cd /home/fred/upstreamlazpaint/lazpaint-6.4.1

fred@fiens ~/u/lazpaint-6.4.1> ./makedeb /home/fred/lazarus/2.0.6
./makedeb: ligne 9: debuild : commande introuvable
```

**Comment by fredvs** [comment] 2020-05-24 20:37
OK, installed `debuild` (with lot of dependencies):

`$ sudo apt install devscripts debhelper`

One more try:

```
$ ./makedeb /home/fred/lazarus/2.0.6
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: paquet source lazpaint
dpkg-buildpackage: info: version source 6.4.1
dpkg-buildpackage: info: distribution source stable
dpkg-buildpackage: info: source changé par circular <circular@operamail.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: architecture hôte amd64
dpkg-checkbuilddeps: erreur: Unmet build dependencies: lazarus-project (>= 1.8.6)
dpkg-buildpackage: avertissement: dépendances de construction et conflits non satisfaits ; échec.
dpkg-buildpackage: avertissement: (Utilisez l'option -d pour forcer.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

Hum, not yet ready to jump into the RPI at the moment, I will need a good internet connection to install all the dependencies.

**Comment by circular17** [comment] 2020-05-24 20:45
> OK, installed `debuild` (with lot of dependencies):

Yes, that's needed for the Debian packaging. How big in MB?

> `dpkg-checkbuilddeps: erreur: Unmet build dependencies: lazarus-project (>= 1.8.6)`

I see. Well in fact, you don't need to install it, because you're compiling with FPC only. Don't install it yet. I need to think of a solution to avoid this error message.

We'll see that another day. I have already spent much time on it today.

**Comment by circular17** [comment] 2020-05-24 20:55
> Hum, not yet ready to jump into the RPI at the moment, I will need a good internet connection to install all the dependencies.

Your Raspberry Pi does not have the same Internet connection?

**Comment by fredvs** [comment] 2020-05-24 21:03
Ha, ok.
I really would prefer to not need to be connected, or if it really indispensable, please not install too much things.

Totally out of the subject:

The goal of `fpc-ootb` is to minimize the installation of unneeded dependencies.
I did already the filter for X11 dependencies, no need to install unneeded dev packages.

But for GTK2, lot of work need to be done.
I will do it for all the dependencies of `GTK2` needed by `LazPaint`.
Normally, if GTK2 is installed (it is the case of Raspbian), fpc should be able to compile `LazPaint` without the need to install all the heavy unneeded dev packages.

But this is a other story totally out of the subject.

**Comment by fredvs** [comment] 2020-05-24 21:05
> Your Raspberry Pi does not have the same Internet connection?

It is connected via the wifi shared by the mobile phone (that works sometimes).

**Comment by fredvs** [comment] 2020-05-24 21:09
> We'll see that another day. I have already spent much time on it today.

Good idea, I will do the same.

Bonne nuit!

**Closed as completed** 2020-06-03 15:08 UTC
